mv /app/sean/tmp/a9* a9/ 
mv /app/sean/tmp/ag* ag/ 
mv /app/sean/tmp/al* al/ 
mv /app/sean/tmp/au* au/ 
mv /app/sean/tmp/bu* bu/ 
mv /app/sean/tmp/c9* c9/ 
mv /app/sean/tmp/CF* CF/ 
mv /app/sean/tmp/cu* cu/ 
mv /app/sean/tmp/FG* FG/ 
mv /app/sean/tmp/i9* i9/ 
mv /app/sean/tmp/j9* j9/ 
mv /app/sean/tmp/jm* jm/ 
mv /app/sean/tmp/l9* l9/ 
mv /app/sean/tmp/m9* m9/ 
mv /app/sean/tmp/MA* MA/ 
mv /app/sean/tmp/ni* ni/ 
mv /app/sean/tmp/OI* OI/ 
mv /app/sean/tmp/p9* p9/ 
mv /app/sean/tmp/rb* rb/ 
mv /app/sean/tmp/RM* RM/ 
mv /app/sean/tmp/SR* SR/ 
mv /app/sean/tmp/TA* TA/ 
mv /app/sean/tmp/v9* v9/ 
mv /app/sean/tmp/y9* y9/ 
mv /app/sean/tmp/zn* zn/
