sh zip-inst.sh a9
sh zip-inst.sh ag
sh zip-inst.sh al
sh zip-inst.sh au
sh zip-inst.sh bu
sh zip-inst.sh c9
sh zip-inst.sh CF
sh zip-inst.sh cu
sh zip-inst.sh FG
sh zip-inst.sh i9
sh zip-inst.sh j9
sh zip-inst.sh jm
sh zip-inst.sh l9
sh zip-inst.sh m9
sh zip-inst.sh MA
sh zip-inst.sh ni
sh zip-inst.sh OI
sh zip-inst.sh p9
sh zip-inst.sh rb
sh zip-inst.sh RM
sh zip-inst.sh SR
sh zip-inst.sh TA
sh zip-inst.sh v9
sh zip-inst.sh y9
sh zip-inst.sh zn
